### ISSUE TITLE
Compilation on AArch64

### ISSUE THREAD

**Issue by afernandezody** [KarypisLab/GKlib#11]
Hello,
Not sure if GKlib has been tested with AArch64 HW but my compilation is producing the error:
```
/tmp/ccij7hPl.s: Assembler messages:
/tmp/ccij7hPl.s:21: Error: unknown mnemonic `clflush' -- `clflush (x3)'
/tmp/ccij7hPl.s:30: Error: unknown mnemonic `sfence' -- `sfence'
make[3]: *** [test/CMakeFiles/gkuniq.dir/build.make:79: test/CMakeFiles/gkuniq.dir/gkuniq.c.o] Error 1
make[3]: Leaving directory '/home/centos/Downloads/GKlib/build/Linux-aarch64'
make[2]: *** [CMakeFiles/Makefile2:409: test/CMakeFiles/gkuniq.dir/all] Error 2
make[2]: Leaving directory '/home/centos/Downloads/GKlib/build/Linux-aarch64'
make[1]: *** [Makefile:139: all] Error 2
make[1]: Leaving directory '/home/centos/Downloads/GKlib/build/Linux-aarch64'
make: *** [Makefile:63: install] Error 2
```
I'm not sure how much assembler is used but it'd obviously need to be modified to run on AArch64. Just a suggestion. Thanks.

**Comment by samuelpmish** [comment]
This issue was marked as "completed" but is seems to still be relevant, see https://github.com/KarypisLab/GKlib/pull/18

**Comment by congunter** [comment]
@afernandezody Did you ever get a fix for this? Currently running into this issue when trying to get METIS install on Apple Silicon.

**Comment by biergaizi** [comment]
> @afernandezody Did you ever get a fix for this? Currently running into this issue when trying to get METIS install on Apple Silicon.

On non-x86, pass `-DNO_X86=1` to cmake, then it should build just fine.
