### ISSUE TITLE
GKlib triggerred an errexit when calling gk_mcorePop->gk_free with multi-thread

### ISSUE THREAD

**Issue by whaleeej** [KarypisLab/GKlib#17]
Hi developer,

This is an issue happening with multi-threading.  When using Metis::METIS_PartGraphRecursive in one thread, everything works ok. However, switching to parallel calls triggers a wired error related to "mallac&free", as illustrated by following image.
![image](https://user-images.githubusercontent.com/34475332/183342206-ecc73d76-4f3c-49df-8cd6-d4c25bd224b0.png)

I have tried to make the static int gk_exit_on_error = 0. But further incertain access voliation would be thrown.

**Comment by mapret** [comment]
I had the same crash with MSVC (which based on your screenshot you are also using), which I fixed in PR #31 .
